### ISSUE TITLE
img Html tag and LaTeX code not compiled properly

### ISSUE THREAD

**Issue by aymeric75** [evanca/quick-portfolio#103]
Hello,

I forked your repo but when editing it, _img Html_ tags and LaTeX code are not compiled properly and appear as text, see this page: https://aymeric75.github.io/nas_page

I cannot find the reason why this is happening, do you have any idea ?

Thanks a lot

**Comment by evanca** [comment]
This project is no longer maintained and has been discontinued. No further updates or support will be provided. Feel free to fork the repository and make any necessary changes on your own.
