### ISSUE TITLE
Add embedded video example

### ISSUE THREAD

**Issue by gregorywmorris** [evanca/quick-portfolio#125]
Embedded Video
Added _includes folder with iframe HTML template.

Video can be linked by using "{% include youtube.html id="enter the youtube ID here" %}"

Credit [Christian Heilmann](https://github.com/codepo8)
Posted on September 14, 2022 [here](https://dev.to/codepo8/quick-tip-embedding-youtube-videos-in-github-pages-4e36)

An example video can be found at the bottom of this page: https://gregorywmorris.github.io/sample_page

folder:
_includes

youtube.html :

`
<div class="embed-container">
    <iframe width="640" height="390" 
    src="https://www.youtube.com/embed/{{ include.id }}" 
    frameborder="0" allowfullscreen></iframe>
</div>
<style>
.embed-container {
  position: relative;
  padding-bottom: 56.25%;
  height: 0;
  overflow: hidden;
  max-width: 100%;
}
.embed-container iframe,
.embed-container object,
.embed-container embed {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}
</style>
`

**Comment by RajivRnjan** [comment]
Hello sir, I can do this effectively so please assign this issue to me.

**Comment by gregorywmorris** [comment]
I have this resolved, I should probably submit a pull request.
