### ISSUE TITLE
Update Google Analytics Integration to GA4

### ISSUE THREAD

**Issue by JYorston** [evanca/quick-portfolio#143]
Universal analytics is being deprecated, so anyone who uses this template will not be able to use the google analytics integration as it is now. 

To update, you can paste the following in the ```_layouts/default.html``` just below the opening `<head>` tag.

```
    {% if site.google_analytics %}
      <script async src="https://www.googletagmanager.com/gtag/js?id={{ site.google_analytics }}"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', '{{ site.google_analytics }}');
    </script>
  {% endif %}
  
  ```
  
  Delete 
  
  ```
      {% if site.google_analytics %}
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
      ga('create', '{{ site.google_analytics }}', 'auto');
      ga('send', 'pageview');
    </script>
    {% endif %}

**Comment by JYorston** [comment]
I've made a branch for this but this repo is not open to PRs.

**Comment by evanca** [comment]
@JYorston I created a branch from this issue, can you check if you can PR now?

**Comment by evanca** [comment]
https://github.com/evanca/quick-portfolio/tree/143-update-google-analytics-integration-to-ga4

**Comment by JYorston** [comment]
Hi @evanca 

I made my commits to your branch but I don't have permission to push them, unfortunately. 

<img width="609" alt="Screenshot 2023-06-12 at 21 49 35" src="https://github.com/evanca/quick-portfolio/assets/7592585/c08ccebe-f58f-410b-84c1-e33c36e9d4cf">
