### ISSUE TITLE
uploading gif files is not possible

### ISSUE THREAD

**Issue by orkhan-amrullayev** [evanca/quick-portfolio#73]
Evanca, thank you for this awesome template. I enjoy it a lot.
However, I could not add .gif files to the index page. I added that file to the images folder and gave the path in the index file, still it did not show up, while there is no any problem with .png or .jpg file types.

PS If I did anything wrong, please apologize me, I am a newbie here.

**Comment by evanca** [comment]
Hi @orkhan-amrullayev! Have you managed to add your gif? I have tried to show a gif file on the main page and on my end it is working well. I have used the following markdown to show animated image:

`<img src="https://media.giphy.com/media/MGdfeiKtEiEPS/giphy.gif?raw=true"/>`

**Comment by orkhan-amrullayev** [comment]
Hi @evanca! Thank you for your attention. It was my fault, after correcting my code, it worked smoothly. Thanks!
