### ISSUE TITLE
Wrong link for open issues in README.md

### ISSUE THREAD

**Issue by anneemorgan** [evanca/quick-portfolio#78]
Expected behavior: Link in README.md to open issues for [quick-portfolio repository](https://github.com/evanca/quick-portfolio/issues).
Actual behavior: Link in README.md to open issues for [machine-learning_optimizing-app-offers-with-starbucks repository](https://github.com/evanca/machine-learning_optimizing-app-offers-with-starbucks/issues).

**Comment by evanca** [comment]
Thanks, resolved with a95abfd
