### ISSUE TITLE
footer can cause the page too compact 

### ISSUE THREAD

**Issue by Zhangjt9317** [evanca/quick-portfolio#9]
Thank you very much for your work. But I found the existence of that footer portion in html code, which you didn't put in the repo, causes overlapping when zooming in to 100%. Would you mind deleting it or sharing the original html code too?

**Comment by evanca** [comment]
Hi @Zhangjt9317! Which file are you referring to? Let me know.

**Comment by dmmello1989** [comment]
Hey @Zhangjt9317 and @evanca !
I'm having the same problem, it's the footer with the text:
"This project is maintained by dmmello1989

Hosted on GitHub Pages — Theme by orderedlist"

It overlaps the description from the _config.yml file. Is there a way to remove this footer entirely?
Also, kinda related to this topic: is there anyway to resize my avatar pic (the logo.png)? I think mine is to big and taking a lot of the description space, maybe causing the footer to overlap.

Thanks in advance!

**Comment by evanca** [comment]
Hi Daniel @dmmello1989. This project is a customized copy of the Minimal theme. To remove the "Hosted on GitHub Pages" footer, you should refer to their documentation:

https://github.com/pages-themes/minimal

> If you'd like to change the theme's HTML layout:

>Copy the original template from the theme's repository
>Create a file called /_layouts/default.html in your site
>Paste the default layout content copied in the first step
>Customize the layout as you'd like

Please let me know if it worked!

**Comment by dmmello1989** [comment]
Hi @evanca, this did the trick, thanks for the quick reply!
