### ISSUE TITLE
pages build and deployment  is failing

### ISSUE THREAD

**Issue by amarahAI** [evanca/quick-portfolio#98]
Hi, when am trying to change my [index.md] file, the change is not reflecting. Could you please help me.

![failed](https://user-images.githubusercontent.com/83214142/179995259-1a69fb4d-e7f9-47ba-a98d-cdc05dfe0044.PNG)

**Comment by aymankhezami** [comment]
Hi @amarahAI , I have the same problem. Did you  manage to find the solution?

**Comment by 907sjl** [comment]
The way to reference themes has changed:
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
